# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [207]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)

In [208]:
print(b)

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [209]:
b.isna()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [210]:
b.isnull()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [211]:
b.isna().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [212]:
b.dropna()

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [213]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [214]:
b['Age'] = b['Age'].fillna(b['Age'].median())

In [215]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob  35.0     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma  35.0    Chennai   95.0

In [216]:
b['City'] = b["City"].fillna(b['City'].mode())

In [217]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob  35.0     Mumbai   91.0
2  Charlie  35.0      Delhi    NaN
3    David  40.0  Bangalore   88.0
4     Emma  35.0    Chennai   95.0

In [218]:
b['Score'] = b["Score"].fillna(0)

In [219]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob  35.0     Mumbai   91.0
2  Charlie  35.0      Delhi    0.0
3    David  40.0  Bangalore   88.0
4     Emma  35.0    Chennai   95.0

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [220]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [221]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [222]:
b['Score'] = b['Score'].astype(float)

In [223]:
b

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [224]:
c = b.copy()

In [225]:
c

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [226]:
c['Name'] = c['Name'].replace("Bob","Robert")

In [227]:
c

      Name  Age  Score
0    Alice   25   88.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [228]:
c['Score'] = c['Score'].replace({88.0:90.00,95.00:102.0})

In [229]:
c

      Name  Age  Score
0    Alice   25   90.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22  102.0

In [230]:
data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Ujjain"]
}

df = pd.DataFrame(data)
# Replace "Bhopal" with "Sehore"
df["City"] = df["City"].replace("Bhopal", "Sehore")

print(df)

     City
0  Sehore
1  Indore
2  Sehore
3  Ujjain

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [231]:
c

      Name  Age  Score
0    Alice   25   90.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22  102.0

In [232]:
c.drop("Age",axis=1)

      Name  Score
0    Alice   90.0
1   Robert   92.0
2  Charlie   79.0
3    David   85.0
4     Emma  102.0

In [233]:
c

      Name  Age  Score
0    Alice   25   90.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22  102.0

In [234]:
c.drop(4,axis=0)

      Name  Age  Score
0    Alice   25   90.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0

In [235]:
c

      Name  Age  Score
0    Alice   25   90.0
1   Robert   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22  102.0

In [236]:
c.drop([1,3])

      Name  Age  Score
0    Alice   25   90.0
2  Charlie   35   79.0
4     Emma   22  102.0

In [237]:
# Drop a row
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Row with index 1 remove
df = df.drop(1)

print(df)

    Name  Age
0   Aman   20
2  Vikas   22

In [238]:
# Drop a column
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})
# Age column remove
df = df.drop("Age", axis=1)

print(df)

    Name
0   Aman
1   Riya
2  Vikas

In [239]:
# Modify dataframe
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Directly modify DataFrame
df.drop("Age", axis=1, inplace=True)

print(df)

    Name
0   Aman
1   Riya
2  Vikas

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [240]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

In [241]:
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

In [242]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [243]:
df.drop_duplicates()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [244]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [245]:
df

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [246]:
df.isna()

    Name    Age   City  Score  Extra
0  False  False  False  False  False
1  False  False  False   True  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5   True  False  False  False  False

In [247]:
df['Age'] = df['Age'].astype(float)
df

     Name   Age       City  Score Extra
0   Alice  25.0      Delhi   85.0     x
1     Bob  30.0     Mumbai    NaN     y
2  Chrlie   NaN        Pun   78.0     z
3   David  40.0  Bangalore   88.0     x
4   Alice  25.0      Delhi   85.0     y
5    None  30.0     Mumbai   91.0     z

In [248]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Score'] = df['Score'].fillna(0)
df['Name'] = df['Name'].fillna("Unknown")
df

      Name   Age       City  Score Extra
0    Alice  25.0      Delhi   85.0     x
1      Bob  30.0     Mumbai    0.0     y
2   Chrlie  30.0        Pun   78.0     z
3    David  40.0  Bangalore   88.0     x
4    Alice  25.0      Delhi   85.0     y
5  Unknown  30.0     Mumbai   91.0     z

In [249]:
df['Age']=df['Age'].astype(int)
df['Score']=df['Score'].astype(float)
df

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2   Chrlie   30        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [250]:
df['City'] = df['City'].replace('Pun','Pune')
df

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2   Chrlie   30       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [251]:
df.drop('Extra',axis=1)

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai    0.0
2   Chrlie   30       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0

In [254]:
df

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2   Chrlie   30       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [255]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Score   6 non-null      float64
 4   Extra   6 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 372.0+ bytes

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.