In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("products-100.csv")

In [54]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [55]:
df.head(5)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

In [56]:
df.tail(5)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [57]:
df.columns

Index(['Index', 'Name', 'Description', 'Brand', 'Category', 'Price',
       'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability',
       'Internal ID'],
      dtype='str')

In [58]:
df.shape

(100, 13)

In [59]:
df.dtypes

Index           int64
Name              str
Description       str
Brand             str
Category          str
Price           int64
Currency          str
Stock           int64
EAN             int64
Color             str
Size              str
Availability      str
Internal ID     int64
dtype: object

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    str
 2   Description   100 non-null    str
 3   Brand         100 non-null    str
 4   Category      100 non-null    str
 5   Price         100 non-null    int64
 6   Currency      100 non-null    str
 7   Stock         100 non-null    int64
 8   EAN           100 non-null    int64
 9   Color         100 non-null    str
 10  Size          100 non-null    str
 11  Availability  100 non-null    str
 12  Internal ID   100 non-null    int64
dtypes: int64(5), str(8)
memory usage: 21.9 KB

In [61]:
df.describe()

            Index      Price       Stock           EAN  Internal ID
count  100.000000  100.00000  100.000000  1.000000e+02   100.000000
mean    50.500000  451.19000  545.710000  4.876267e+12    49.340000
std     29.011492  281.60911  266.716863  2.918084e+12    28.078253
min      1.000000    1.00000   10.000000  5.246382e+08     3.000000
25%     25.750000  230.75000  347.500000  2.062323e+12    25.000000
50%     50.500000  407.50000  575.500000  4.875720e+12    48.000000
75%     75.250000  679.00000  749.250000  7.676943e+12    74.500000
max    100.000000  999.00000  998.000000  9.921752e+12    99.000000

In [62]:
df.describe(include='all')

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
count,100.000000,100,100,100,100,100.00000,100,100.000000,1.000000e+02,100,100,100,100.000000
unique,NaN,99,100,100,32,NaN,1,NaN,NaN,72,17,6,NaN
top,NaN,Tablet,Situation organization these memory much off.,"Garner, Boyle and Flynn",Automotive,NaN,USD,NaN,NaN,Cyan,L,pre_order,NaN
freq,NaN,2,1,1,6,NaN,100,NaN,NaN,4,10,25,NaN
mean,50.500000,NaN,NaN,NaN,NaN,451.19000,NaN,545.710000,4.876267e+12,NaN,NaN,NaN,49.340000
std,29.011492,NaN,NaN,NaN,NaN,281.60911,NaN,266.716863,2.918084e+12,NaN,NaN,NaN,28.078253
min,1.000000,NaN,NaN,NaN,NaN,1.00000,NaN,10.000000,5.246382e+08,NaN,NaN,NaN,3.000000
25%,25.750000,NaN,NaN,NaN,NaN,230.75000,NaN,347.500000,2.062323e+12,NaN,NaN,NaN,25.000000
50%,50.500000,NaN,NaN,NaN,NaN,407.50000,NaN,575.500000,4.875720e+12,NaN,NaN,NaN,48.000000
75%,75.250000,NaN,NaN,NaN,NaN,679.00000,NaN,749.250000,7.676943e+12,NaN,NaN,NaN,74.500000
max,100.000000,NaN,NaN,NaN,NaN,999.00000,NaN,998.000000,9.921752e+12,NaN,NaN,NaN,99.000000

In [63]:
df.isna()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False

In [64]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Index, Name, Description, Brand, Category, Price, Currency, Stock, EAN, Color, Size, Availability, Internal ID]
Index: []

In [65]:
df.isna().sum()

Index           0
Name            0
Description     0
Brand           0
Category        0
Price           0
Currency        0
Stock           0
EAN             0
Color           0
Size            0
Availability    0
Internal ID     0
dtype: int64

In [66]:
df.isna().any()

Index           False
Name            False
Description     False
Brand           False
Category        False
Price           False
Currency        False
Stock           False
EAN             False
Color           False
Size            False
Availability    False
Internal ID     False
dtype: bool

In [67]:
df.isna().sum().sum()

np.int64(0)

In [68]:
df.isna().any().any()

np.False_

In [69]:
df[['Name','Price']]

                                     Name  Price
0    Compact Printer Air Advanced Digital    265
1                                  Tablet    502
2                    Smart Blender Cooker    227
3            Advanced Router Rechargeable    121
4            Portable Mouse Monitor Phone      1
..                                    ...    ...
95                                 Router    375
96     Fast Thermostat Microphone Scooter    289
97  Eco Heater Toaster Stove Silent Sense    232
98               Clean Blender Scale Lite    241
99                             Smart Lamp     71

[100 rows x 2 columns]

In [70]:
df[df['Price']>500]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
9,10,Ultra Powerbank Brush Charger Max,Meeting add economic task outside.,"Brennan, Archer and Rosales",Fitness Equipment,845,USD,564,4877111475333,Silver,Extra Large,discontinued,88
12,13,Heater Radio,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD,156,5686660235911,Orange,L,pre_order,57
16,17,Eco Iron Monitor Air,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD,47,7887280730963,OliveDrab,XL,out_of_stock,79
19,20,Cooler Fan,Fall billion city share.,Bray LLC,Smartphones,529,USD,844,267078141619,Bisque,XS,backorder,22
21,22,Wireless Powerbank 360 Advanced Ultra,Deal head decade age outside military culture.,Carney Ltd,Bedding & Bath,677,USD,418,3918763032312,Beige,M,out_of_stock,90
22,23,Rechargeable Lamp Speakerphone Headphones,Effort own safe main walk quickly.,"Gallegos, Osborne and Carpenter",Skincare,664,USD,577,1824359393441,DarkBlue,L,pre_order,26
23,24,Mini Scooter Microphone,Maybe around expect own whether pay.,"Douglas, Thornton and Soto",Grooming Tools,784,USD,510,9839666739792,DimGray,L,backorder,55
24,25,Rechargeable Webcam Stove Grill,Movement you Mr decide history effect.,Horn-Pope,Health & Wellness,900,USD,623,6501687247749,PaleGreen,5x7 in,out_of_stock,47
25,26,Mini Iron Drone Wireless Pro,From Congress low.,Khan-Parrish,Cycling,909,USD,797,9496081864722,CadetBlue,XXL,limited_stock,93
27,28,Wireless Webcam Stove Grill,Pull at improve health also animal forward per...,Henry Group,Clothing & Apparel,858,USD,912,7097613907430,LightSalmon,50x70 cm,limited_stock,43
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
29,30,Keyboard Toaster Monitor,My head prove exist change.,Bonilla-Spears,Kids' Clothing,576,USD,988,6639325474032,DarkSlateGray,L,pre_order,40
32,33,Advanced Microphone Cooler Eco,Most other newspaper beyond real.,"Morales, Weaver and Fernandez",Smartphones,904,USD,532,7107438924403,LightCyan,Extra Large,limited_stock,86
35,36,Smart Phone Scooter Clean,Reality kid create thought window.,Marshall-Dougherty,Women's Clothing,635,USD,727,7883295446066,MediumVioletRed,10x10 cm,backorder,74
37,38,Ultra Dock Trimmer Automatic Edge,Do customer stage act send.,Barnes-Glass,Kids' Clothing,640,USD,780,2837107354495,LightBlue,5x7 in,discontinued,96
38,39,Wireless Tablet Router Printer Wireless Premiu...,North meeting short summer situation positive ...,Meyers-Hess,Sports & Outdoors,781,USD,947,8247903213713,BlanchedAlmond,XL,out_of_stock,69
39,40,Clean Printer Advanced Premium Sense,Bag away always often join seat direction.,Williamson PLC,Haircare,913,USD,820,5234087663802,Moccasin,Small,discontinued,77
41,42,Ultra Speakerphone Oven Go Smart X,Value bill yeah tell phone.,"Zimmerman, Barr and Davis",Office Supplies,999,USD,853,450118214736,MediumOrchid,12x18 in,pre_order,23
42,43,Rechargeable Projector Pro,Bank everything ago girl.,"Levine, Martin and Mccann",Home Decor,935,USD,55,655296358115,SlateBlue,XL,limited_stock,52
46,47,Portable Powerbank X Air,Present court note medical bed red movie.,Hanson-Schultz,Camping & Hiking,599,USD,263,6854117854742,Moccasin,Large,discontinued,17
47,48,Clock,Onto story what job require.,"Malone, Jacobson and Hudson",Team Sports,731,USD,664,1382809012286,FloralWhite,S,limited_stock,55
48,49,Radio Treadmill,Through choose record prove happen.,Barron-Little,Office Supplies,511,USD,395,5461960384619,Violet,XL,discontinued,14
50,51,Mini Fridge Camera,Little determine at huge month.,Decker and Sons,Fitness Equipment,777,USD,832,4894233116968,PaleGoldenRod,Extra Large,in_stock,16
51,52,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
53,54,Wireless Light Toaster Lite Touch Eco,Oil guy table industry hand which.,Singleton PLC,Bedding & Bath,791,USD,827,3057639268476,Fuchsia,50x70 cm,in_stock,64
56,57,Ultra Keyboard Compact Eco,Bit responsibility cover him mean call civil.,Pace-Hodges,Books & Stationery,514,USD,491,8481605893389,LightGray,8x10 in,backorder,19
57,58,Portable Scale Speaker Powerbank Clean,Throughout special new you view season within.,Morris LLC,Women's Clothing,689,USD,332,5175038823985,PowderBlue,Small,backorder,94
59,60,Automatic Speaker Router Lamp Prime,Word score education thousand high treatment.,"Sexton, Dickerson and Blair",Grooming Tools,621,USD,667,6744198567221,FireBrick,5x7 in,in_stock,61
61,62,Fast Fan,Avoid very final food scene possible.,Ali-Oliver,Cleaning Supplies,982,USD,804,3388615003133,DarkOrchid,100x200 mm,backorder,70
65,66,Treadmill,Vote only run modern.,"Frost, Christensen and Burnett",Women's Clothing,731,USD,744,4598541150958,Cyan,5x7 in,out_of_stock,70
66,67,Mini Charger Lock Oven Sense Sense,Major tell him share allow.,"Burton, Gross and Giles",Haircare,750,USD,623,9282813513019,Olive,12x18 in,in_stock,81
72,73,Compact Thermostat Oven,Focus that consumer amount half.,Hull Inc,Home & Kitchen,685,USD,747,7695934105636,SaddleBrown,30x40 cm,in_stock,36
74,75,Automatic Blender,Smile human machine section bank.,Mahoney-Bryan,Home Decor,630,USD,438,310774792552,LightGoldenRodYellow,8x10 in,backorder,4
75,76,Rechargeable Webcam Dock Heater,Organization address section collection church...,Kennedy-Gordon,Cycling,800,USD,151,1340784358003,Brown,XXL,in_stock,66
79,80,Rechargeable Brush Compact,Early century every amount than past.,Castro-Mccarty,Automotive,748,USD,326,6855062072649,Sienna,S,out_of_stock,81
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64
86,87,Silent Speakerphone Scanner Monitor,Quality yet significant lawyer face field yet ...,Cowan Inc,Fragrances,593,USD,580,1710131812265,Navy,XXL,discontinued,20
89,90,Digital Trimmer,Ago floor nice member wait.,Christian-Tanner,Laptops & Computers,541,USD,488,4147810179628,SteelBlue,M,pre_order,31
91,92,Portable Scooter Wireless Digital,Thousand various evidence.,Bauer Inc,Cameras & Accessories,519,USD,495,4564280934296,DeepSkyBlue,Large,in_stock,36

In [71]:
df[df['Stock']<20]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
80,81,Fast Heater Cooker Compact Silent,Strategy fund mind rather change.,"Decker, Montes and Logan",Makeup,367,USD,19,3868467036959,Orchid,8x10 in,in_stock,15
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64

In [72]:
df[df['Availability']=='in_stock']

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
20,21,Portable Camera Plus Air Ultra,Reality hair explain up bad.,Wang-Valenzuela,Women's Clothing,197,USD,163,963840013930,Magenta,L,in_stock,96
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
43,44,Eco Vacuum,Bit name seat sea.,Werner PLC,Health & Wellness,259,USD,668,8611986118980,LightCoral,5x7 in,in_stock,45
50,51,Mini Fridge Camera,Little determine at huge month.,Decker and Sons,Fitness Equipment,777,USD,832,4894233116968,PaleGoldenRod,Extra Large,in_stock,16
51,52,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
53,54,Wireless Light Toaster Lite Touch Eco,Oil guy table industry hand which.,Singleton PLC,Bedding & Bath,791,USD,827,3057639268476,Fuchsia,50x70 cm,in_stock,64
59,60,Automatic Speaker Router Lamp Prime,Word score education thousand high treatment.,"Sexton, Dickerson and Blair",Grooming Tools,621,USD,667,6744198567221,FireBrick,5x7 in,in_stock,61
60,61,Smart Webcam Projector Lock,Subject agree you off.,Stokes Inc,Men's Clothing,440,USD,973,4811928042234,SteelBlue,Medium,in_stock,3
64,65,Silent Trimmer Shaver Fast,Task point seat better.,Munoz Group,Smartphones,130,USD,876,4089415274929,DarkSlateGray,5x7 in,in_stock,76
66,67,Mini Charger Lock Oven Sense Sense,Major tell him share allow.,"Burton, Gross and Giles",Haircare,750,USD,623,9282813513019,Olive,12x18 in,in_stock,81
72,73,Compact Thermostat Oven,Focus that consumer amount half.,Hull Inc,Home & Kitchen,685,USD,747,7695934105636,SaddleBrown,30x40 cm,in_stock,36
75,76,Rechargeable Webcam Dock Heater,Organization address section collection church...,Kennedy-Gordon,Cycling,800,USD,151,1340784358003,Brown,XXL,in_stock,66
77,78,Brush,Control daughter effect investment piece train...,"Lowe, Mosley and Rivera",Bedding & Bath,273,USD,623,168419438521,RoyalBlue,S,in_stock,42
80,81,Fast Heater Cooker Compact Silent,Strategy fund mind rather change.,"Decker, Montes and Logan",Makeup,367,USD,19,3868467036959,Orchid,8x10 in,in_stock,15
83,84,Wireless Fan Thermostat Max Automatic Max,Design price for especially section college ov...,Kaiser-Banks,Books & Stationery,423,USD,759,1396411470228,MidnightBlue,5x7 in,in_stock,81
90,91,Automatic Trimmer Sense,Much table ground information news senior.,Harrington-Valentine,Kitchen Appliances,405,USD,950,524638185,SlateGray,8x10 in,in_stock,85
91,92,Portable Scooter Wireless Digital,Thousand various evidence.,Bauer Inc,Cameras & Accessories,519,USD,495,4564280934296,DeepSkyBlue,Large,in_stock,36
92,93,Fridge Cooker,Try better loss pretty special.,Jackson Group,Furniture,393,USD,499,1861389468671,Black,Small,in_stock,80

In [73]:
len(df[df['Availability']=='in_stock'])

20

In [76]:
df[df['Brand']=='Sony']

Empty DataFrame
Columns: [Index, Name, Description, Brand, Category, Price, Currency, Stock, EAN, Color, Size, Availability, Internal ID]
Index: []

In [77]:
df[(df['Price']>=200)&(df['Price']<=800)]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,Ultra Radio Radio,Shoulder red boy away if.,Maldonado-Ritter,Haircare,382,USD,639,3611080124547,Aquamarine,12x18 in,pre_order,48
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5

In [79]:
df.iloc[:21]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
6,7,Ultra Projector Oven Thermostat Prime Advanced,Pattern possible look necessary indicate work ...,"Mccoy, Waters and Rose",Laptops & Computers,68,USD,870,5029747624534,Purple,S,discontinued,86
7,8,Webcam Stove Grill,Deep area join carry age.,Morrow and Sons,Automotive,159,USD,584,9883725074294,MediumOrchid,8x10 in,pre_order,50
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88
9,10,Ultra Powerbank Brush Charger Max,Meeting add economic task outside.,"Brennan, Archer and Rosales",Fitness Equipment,845,USD,564,4877111475333,Silver,Extra Large,discontinued,88
10,11,Wireless Dock,Whole bill sound whether will.,Russo-West,Health & Wellness,257,USD,168,9680811891595,Wheat,Extra Large,pre_order,30
11,12,Fast Camera Router Fan Smart,Various above trouble itself crime form.,Vazquez and Sons,Cleaning Supplies,221,USD,672,8567222480604,MidnightBlue,Medium,pre_order,32
12,13,Heater Radio,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD,156,5686660235911,Orange,L,pre_order,57
13,14,Smart Trimmer Webcam Heater,Example available better.,Contreras PLC,Automotive,279,USD,818,1941032767914,Gainsboro,XXL,pre_order,66
14,15,Webcam Dock Heater,State yet soon traditional your deal.,"Juarez, Powell and Travis",Cleaning Supplies,101,USD,159,1438856474369,Sienna,30x40 cm,pre_order,88
15,16,Automatic Watch Lite Sense,As east entire positive source their.,"Reid, Chase and Ballard",Team Sports,316,USD,329,3500722785805,Tan,5x7 in,limited_stock,44
16,17,Eco Iron Monitor Air,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD,47,7887280730963,OliveDrab,XL,out_of_stock,79
17,18,Digital Tablet Router Printer Lite,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD,732,4170125892616,LemonChiffon,10x10 cm,backorder,87
18,19,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
19,20,Cooler Fan,Fall billion city share.,Bray LLC,Smartphones,529,USD,844,267078141619,Bisque,XS,backorder,22
20,21,Portable Camera Plus Air Ultra,Reality hair explain up bad.,Wang-Valenzuela,Women's Clothing,197,USD,163,963840013930,Magenta,L,in_stock,96

In [81]:
df.iloc[10:21,2:7]

,Description,Brand,Category,Price,Currency
10,Whole bill sound whether will.,Russo-West,Health & Wellness,257,USD
11,Various above trouble itself crime form.,Vazquez and Sons,Cleaning Supplies,221,USD
12,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD
13,Example available better.,Contreras PLC,Automotive,279,USD
14,State yet soon traditional your deal.,"Juarez, Powell and Travis",Cleaning Supplies,101,USD
15,As east entire positive source their.,"Reid, Chase and Ballard",Team Sports,316,USD
16,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD
17,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD
18,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD
19,Fall billion city share.,Bray LLC,Smartphones,529,USD
20,Reality hair explain up bad.,Wang-Valenzuela,Women's Clothing,197,USD

In [82]:
df[(df['Price']>500) & (df['Stock']>50)]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
9,10,Ultra Powerbank Brush Charger Max,Meeting add economic task outside.,"Brennan, Archer and Rosales",Fitness Equipment,845,USD,564,4877111475333,Silver,Extra Large,discontinued,88
12,13,Heater Radio,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD,156,5686660235911,Orange,L,pre_order,57
19,20,Cooler Fan,Fall billion city share.,Bray LLC,Smartphones,529,USD,844,267078141619,Bisque,XS,backorder,22
21,22,Wireless Powerbank 360 Advanced Ultra,Deal head decade age outside military culture.,Carney Ltd,Bedding & Bath,677,USD,418,3918763032312,Beige,M,out_of_stock,90
22,23,Rechargeable Lamp Speakerphone Headphones,Effort own safe main walk quickly.,"Gallegos, Osborne and Carpenter",Skincare,664,USD,577,1824359393441,DarkBlue,L,pre_order,26
23,24,Mini Scooter Microphone,Maybe around expect own whether pay.,"Douglas, Thornton and Soto",Grooming Tools,784,USD,510,9839666739792,DimGray,L,backorder,55
24,25,Rechargeable Webcam Stove Grill,Movement you Mr decide history effect.,Horn-Pope,Health & Wellness,900,USD,623,6501687247749,PaleGreen,5x7 in,out_of_stock,47
25,26,Mini Iron Drone Wireless Pro,From Congress low.,Khan-Parrish,Cycling,909,USD,797,9496081864722,CadetBlue,XXL,limited_stock,93
27,28,Wireless Webcam Stove Grill,Pull at improve health also animal forward per...,Henry Group,Clothing & Apparel,858,USD,912,7097613907430,LightSalmon,50x70 cm,limited_stock,43
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
29,30,Keyboard Toaster Monitor,My head prove exist change.,Bonilla-Spears,Kids' Clothing,576,USD,988,6639325474032,DarkSlateGray,L,pre_order,40
32,33,Advanced Microphone Cooler Eco,Most other newspaper beyond real.,"Morales, Weaver and Fernandez",Smartphones,904,USD,532,7107438924403,LightCyan,Extra Large,limited_stock,86
35,36,Smart Phone Scooter Clean,Reality kid create thought window.,Marshall-Dougherty,Women's Clothing,635,USD,727,7883295446066,MediumVioletRed,10x10 cm,backorder,74
37,38,Ultra Dock Trimmer Automatic Edge,Do customer stage act send.,Barnes-Glass,Kids' Clothing,640,USD,780,2837107354495,LightBlue,5x7 in,discontinued,96
38,39,Wireless Tablet Router Printer Wireless Premiu...,North meeting short summer situation positive ...,Meyers-Hess,Sports & Outdoors,781,USD,947,8247903213713,BlanchedAlmond,XL,out_of_stock,69
39,40,Clean Printer Advanced Premium Sense,Bag away always often join seat direction.,Williamson PLC,Haircare,913,USD,820,5234087663802,Moccasin,Small,discontinued,77
41,42,Ultra Speakerphone Oven Go Smart X,Value bill yeah tell phone.,"Zimmerman, Barr and Davis",Office Supplies,999,USD,853,450118214736,MediumOrchid,12x18 in,pre_order,23
42,43,Rechargeable Projector Pro,Bank everything ago girl.,"Levine, Martin and Mccann",Home Decor,935,USD,55,655296358115,SlateBlue,XL,limited_stock,52
46,47,Portable Powerbank X Air,Present court note medical bed red movie.,Hanson-Schultz,Camping & Hiking,599,USD,263,6854117854742,Moccasin,Large,discontinued,17
47,48,Clock,Onto story what job require.,"Malone, Jacobson and Hudson",Team Sports,731,USD,664,1382809012286,FloralWhite,S,limited_stock,55
48,49,Radio Treadmill,Through choose record prove happen.,Barron-Little,Office Supplies,511,USD,395,5461960384619,Violet,XL,discontinued,14
50,51,Mini Fridge Camera,Little determine at huge month.,Decker and Sons,Fitness Equipment,777,USD,832,4894233116968,PaleGoldenRod,Extra Large,in_stock,16
51,52,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
53,54,Wireless Light Toaster Lite Touch Eco,Oil guy table industry hand which.,Singleton PLC,Bedding & Bath,791,USD,827,3057639268476,Fuchsia,50x70 cm,in_stock,64
56,57,Ultra Keyboard Compact Eco,Bit responsibility cover him mean call civil.,Pace-Hodges,Books & Stationery,514,USD,491,8481605893389,LightGray,8x10 in,backorder,19
57,58,Portable Scale Speaker Powerbank Clean,Throughout special new you view season within.,Morris LLC,Women's Clothing,689,USD,332,5175038823985,PowderBlue,Small,backorder,94
59,60,Automatic Speaker Router Lamp Prime,Word score education thousand high treatment.,"Sexton, Dickerson and Blair",Grooming Tools,621,USD,667,6744198567221,FireBrick,5x7 in,in_stock,61
61,62,Fast Fan,Avoid very final food scene possible.,Ali-Oliver,Cleaning Supplies,982,USD,804,3388615003133,DarkOrchid,100x200 mm,backorder,70
65,66,Treadmill,Vote only run modern.,"Frost, Christensen and Burnett",Women's Clothing,731,USD,744,4598541150958,Cyan,5x7 in,out_of_stock,70
66,67,Mini Charger Lock Oven Sense Sense,Major tell him share allow.,"Burton, Gross and Giles",Haircare,750,USD,623,9282813513019,Olive,12x18 in,in_stock,81
72,73,Compact Thermostat Oven,Focus that consumer amount half.,Hull Inc,Home & Kitchen,685,USD,747,7695934105636,SaddleBrown,30x40 cm,in_stock,36
74,75,Automatic Blender,Smile human machine section bank.,Mahoney-Bryan,Home Decor,630,USD,438,310774792552,LightGoldenRodYellow,8x10 in,backorder,4
75,76,Rechargeable Webcam Dock Heater,Organization address section collection church...,Kennedy-Gordon,Cycling,800,USD,151,1340784358003,Brown,XXL,in_stock,66
79,80,Rechargeable Brush Compact,Early century every amount than past.,Castro-Mccarty,Automotive,748,USD,326,6855062072649,Sienna,S,out_of_stock,81
86,87,Silent Speakerphone Scanner Monitor,Quality yet significant lawyer face field yet ...,Cowan Inc,Fragrances,593,USD,580,1710131812265,Navy,XXL,discontinued,20
89,90,Digital Trimmer,Ago floor nice member wait.,Christian-Tanner,Laptops & Computers,541,USD,488,4147810179628,SteelBlue,M,pre_order,31
91,92,Portable Scooter Wireless Digital,Thousand various evidence.,Bauer Inc,Cameras & Accessories,519,USD,495,4564280934296,DeepSkyBlue,Large,in_stock,36

In [83]:
len(df[(df['Price']>500) & (df['Stock']>50)])

38

In [84]:
df.sort_values("Price",ascending=True)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
17,18,Digital Tablet Router Printer Lite,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD,732,4170125892616,LemonChiffon,10x10 cm,backorder,87
69,70,Compact Mouse Mouse Router Mini,Occur miss son Democrat happy.,Barry PLC,Smartwatches,5,USD,247,252926529077,PapayaWhip,10x10 cm,limited_stock,79
70,71,Premium Lock Mini Advanced,Three character traditional maybe.,"Elliott, Mcfarland and Duran",Automotive,12,USD,439,3997003361528,Plum,XS,pre_order,40
87,88,Silent Scanner Monitor Treadmill,Do interesting suggest agreement range admit r...,"Nichols, Howe and Miller",Health & Wellness,30,USD,728,1287056757693,Wheat,10x10 cm,pre_order,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,62,Fast Fan,Avoid very final food scene possible.,Ali-Oliver,Cleaning Supplies,982,USD,804,3388615003133,DarkOrchid,100x200 mm,backorder,70
16,17,Eco Iron Monitor Air,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD,47,7887280730963,OliveDrab,XL,out_of_stock,79
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64
41,42,Ultra Speakerphone Oven Go Smart X,Value bill yeah tell phone.,"Zimmerman, Barr and Davis",Office Supplies,999,USD,853,450118214736,MediumOrchid,12x18 in,pre_order,23

In [85]:
df[df['Price'].between(200,800)]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,Ultra Radio Radio,Shoulder red boy away if.,Maldonado-Ritter,Haircare,382,USD,639,3611080124547,Aquamarine,12x18 in,pre_order,48
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5

In [86]:
df1 = df[df['Availability'] == 'in_stock']

In [90]:
df1[['Name','Price','Availability']]

                                         Name  Price Availability
1                                      Tablet    502     in_stock
2                        Smart Blender Cooker    227     in_stock
20             Portable Camera Plus Air Ultra    197     in_stock
28                                Clock Brush    985     in_stock
43                                 Eco Vacuum    259     in_stock
50                         Mini Fridge Camera    777     in_stock
51     Rechargeable Tablet Plus Portable Mini    820     in_stock
53      Wireless Light Toaster Lite Touch Eco    791     in_stock
59        Automatic Speaker Router Lamp Prime    621     in_stock
60                Smart Webcam Projector Lock    440     in_stock
64                 Silent Trimmer Shaver Fast    130     in_stock
66         Mini Charger Lock Oven Sense Sense    750     in_stock
72                    Compact Thermostat Oven    685     in_stock
75            Rechargeable Webcam Dock Heater    800     in_stock
77                                      Brush    273     in_stock
80          Fast Heater Cooker Compact Silent    367     in_stock
83  Wireless Fan Thermostat Max Automatic Max    423     in_stock
90                    Automatic Trimmer Sense    405     in_stock
91          Portable Scooter Wireless Digital    519     in_stock
92                              Fridge Cooker    393     in_stock

In [91]:
df[(df['Price']>500) & (df['Availability']=='in_stock')]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
50,51,Mini Fridge Camera,Little determine at huge month.,Decker and Sons,Fitness Equipment,777,USD,832,4894233116968,PaleGoldenRod,Extra Large,in_stock,16
51,52,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
53,54,Wireless Light Toaster Lite Touch Eco,Oil guy table industry hand which.,Singleton PLC,Bedding & Bath,791,USD,827,3057639268476,Fuchsia,50x70 cm,in_stock,64
59,60,Automatic Speaker Router Lamp Prime,Word score education thousand high treatment.,"Sexton, Dickerson and Blair",Grooming Tools,621,USD,667,6744198567221,FireBrick,5x7 in,in_stock,61
66,67,Mini Charger Lock Oven Sense Sense,Major tell him share allow.,"Burton, Gross and Giles",Haircare,750,USD,623,9282813513019,Olive,12x18 in,in_stock,81
72,73,Compact Thermostat Oven,Focus that consumer amount half.,Hull Inc,Home & Kitchen,685,USD,747,7695934105636,SaddleBrown,30x40 cm,in_stock,36
75,76,Rechargeable Webcam Dock Heater,Organization address section collection church...,Kennedy-Gordon,Cycling,800,USD,151,1340784358003,Brown,XXL,in_stock,66
91,92,Portable Scooter Wireless Digital,Thousand various evidence.,Bauer Inc,Cameras & Accessories,519,USD,495,4564280934296,DeepSkyBlue,Large,in_stock,36

In [92]:
df2 = df[df['Stock']<20]

In [93]:
df2

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
80,81,Fast Heater Cooker Compact Silent,Strategy fund mind rather change.,"Decker, Montes and Logan",Makeup,367,USD,19,3868467036959,Orchid,8x10 in,in_stock,15
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64

In [94]:
df2[['Name','Brand','Stock']]

                                 Name                     Brand  Stock
80  Fast Heater Cooker Compact Silent  Decker, Montes and Logan     19
84                      Fast Keyboard                 Lewis Ltd     10

In [96]:
df[(df['Stock']<20) & (df['Price']>700)]

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64

In [97]:
df[df['Availability'] == 'in_stock'][['Name','Price']]

                                         Name  Price
1                                      Tablet    502
2                        Smart Blender Cooker    227
20             Portable Camera Plus Air Ultra    197
28                                Clock Brush    985
43                                 Eco Vacuum    259
50                         Mini Fridge Camera    777
51     Rechargeable Tablet Plus Portable Mini    820
53      Wireless Light Toaster Lite Touch Eco    791
59        Automatic Speaker Router Lamp Prime    621
60                Smart Webcam Projector Lock    440
64                 Silent Trimmer Shaver Fast    130
66         Mini Charger Lock Oven Sense Sense    750
72                    Compact Thermostat Oven    685
75            Rechargeable Webcam Dock Heater    800
77                                      Brush    273
80          Fast Heater Cooker Compact Silent    367
83  Wireless Fan Thermostat Max Automatic Max    423
90                    Automatic Trimmer Sense    405
91          Portable Scooter Wireless Digital    519
92                              Fridge Cooker    393