# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [ ]:
df

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [ ]:
df.value_counts('Department')

Department
Finance    3
IT         3
HR         2
Name: count, dtype: int64

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [ ]:
df[df['Department']=='IT']['Salary'].mean()

np.float64(72333.33333333333)

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')

In [ ]:
df.groupby('Department')['Employee'].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [ ]:
df.groupby('Department')['Salary'].agg(["mean","max",'min',])

                    mean    max    min
Department
Finance     61000.000000  65000  58000
HR          51000.000000  52000  50000
IT          72333.333333  75000  70000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [ ]:
df.groupby("Department").agg({
    "Salary":['mean','max','min'],
    "Age":['mean','max']
})

                  Salary                      Age
                    mean    max    min       mean max
Department
Finance     61000.000000  65000  58000  29.333333  35
HR          51000.000000  52000  50000  28.500000  29
IT          72333.333333  75000  70000  31.000000  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
df["AgeGroup"] = pd.cut(df["Age"], bins=[25, 30, 35, 40], labels=["25-30", "31-35", "36-40"])
crosstab_result = pd.crosstab(df["Department"], df["AgeGroup"])
df

  Employee Department  Salary  Age AgeGroup
0     John         HR   50000   28    25-30
1    Sarah         IT   70000   32    31-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [ ]:
df.pivot_table(values='Salary',index='Department',aggfunc='mean')

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [ ]:
import seaborn as sas

In [ ]:
df = sas.load_dataset('flights')

In [ ]:
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
df.value_counts('year')

year
1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: count, dtype: int64

In [ ]:
df.pivot_table(values='passengers',index='year',columns='month')

/tmp/ipykernel_643/194409501.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values='passengers',index='year',columns='month')

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [ ]:
df.pivot_table(values='passengers',index='year',columns='month',aggfunc='mean')

/tmp/ipykernel_643/2456317735.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values='passengers',index='year',columns='month',aggfunc='mean')

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

In [ ]:
import pandas as pd

data = {
    "Department": [
        "IT", "HR", "Finance", "Marketing", "Sales",
        "IT", "HR", "Finance", "Marketing", "Sales",
        "IT", "HR", "Finance", "Marketing", "Sales"
    ],
    "Employee": [
        "Alice", "Bob", "Charlie", "David", "Emma",
        "Frank", "Grace", "Henry", "Isabella", "Jack",
        "Kevin", "Lily", "Michael", "Nancy", "Oliver"
    ],
    "Salary": [
        65000, 50000, 72000, 58000, 61000,
        70000, 52000, 76000, 60000, 63000,
        82000, 54000, 78000, 62000, 68000
    ],
    "Age": [
        25, 30, 35, 28, 32,
        27, 31, 40, 29, 33,
        38, 26, 42, 34, 36
    ],
    "City": [
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar",
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar",
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"
    ]
}

df = pd.DataFrame(data)

In [ ]:
df

   Department  Employee  Salary  Age         City
0          IT     Alice   65000   25    Ahmedabad
1          HR       Bob   50000   30        Surat
2     Finance   Charlie   72000   35     Vadodara
3   Marketing     David   58000   28       Rajkot
4       Sales      Emma   61000   32  Gandhinagar
5          IT     Frank   70000   27    Ahmedabad
6          HR     Grace   52000   31        Surat
7     Finance     Henry   76000   40     Vadodara
8   Marketing  Isabella   60000   29       Rajkot
9       Sales      Jack   63000   33  Gandhinagar
10         IT     Kevin   82000   38    Ahmedabad
11         HR      Lily   54000   26        Surat
12    Finance   Michael   78000   42     Vadodara
13  Marketing     Nancy   62000   34       Rajkot
14      Sales    Oliver   68000   36  Gandhinagar

In [ ]:
df.groupby('Department').agg({
    "Salary":['mean'],
    "Age":['max']
})

                  Salary Age
                    mean max
Department
Finance     75333.333333  42
HR          52000.000000  31
IT          72333.333333  38
Marketing   60000.000000  34
Sales       64000.000000  36

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance      75333.333333
HR           52000.000000
IT           72333.333333
Marketing    60000.000000
Sales        64000.000000
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Age'].max()

Department
Finance      42
HR           31
IT           38
Marketing    34
Sales        36
Name: Age, dtype: int64

In [ ]:
df.pivot_table(values='Salary',index='Department',columns='City',aggfunc='mean')

City           Ahmedabad  Gandhinagar   Rajkot    Surat      Vadodara
Department
Finance              NaN          NaN      NaN      NaN  75333.333333
HR                   NaN          NaN      NaN  52000.0           NaN
IT          72333.333333          NaN      NaN      NaN           NaN
Marketing            NaN          NaN  60000.0      NaN           NaN
Sales                NaN      64000.0      NaN      NaN           NaN

In [ ]:
df.pivot_table(values='Salary',index='Department',columns='City',aggfunc='mean',fill_value=0)

City           Ahmedabad  Gandhinagar   Rajkot    Surat      Vadodara
Department
Finance         0.000000          0.0      0.0      0.0  75333.333333
HR              0.000000          0.0      0.0  52000.0      0.000000
IT          72333.333333          0.0      0.0      0.0      0.000000
Marketing       0.000000          0.0  60000.0      0.0      0.000000
Sales           0.000000      64000.0      0.0      0.0      0.000000

In [ ]:
pd.crosstab(
    df["Department"],
    df["City"]
)

City        Ahmedabad  Gandhinagar  Rajkot  Surat  Vadodara
Department
Finance             0            0       0      0         3
HR                  0            0       0      3         0
IT                  3            0       0      0         0
Marketing           0            0       3      0         0
Sales               0            3       0      0         0

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.