# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [14]:
import pandas as pd

data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],

    "OrderDate": [
        "2024-01-05",
        "2024/01/12",
        "15-01-2024",
        "2024-01-20",
        "20240125"
    ],

    "Customer": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Emma"
    ],

    "Amount": [
        250,
        400,
        150,
        300,
        500
    ]
}

df = pd.DataFrame(data)

In [15]:
df

   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

In [16]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'],errors='coerce')

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [17]:
df_inx = df.set_index("OrderDate")
df_inx

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
NaT            1002      Bob     400
NaT            1003  Charlie     150
2024-01-20     1004    David     300
NaT            1005     Emma     500

In [18]:
df_inx.resample("M")['Amount'].sum()

/tmp/ipykernel_902/4143240648.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_inx.resample("M")['Amount'].sum()

OrderDate
2024-01-31    550
Name: Amount, dtype: int64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [19]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

# 2️⃣ Convert VisitDate to datetime
# Write your code here

# 3️⃣ Set VisitDate as the index
# Write your code here

# 4️⃣ Resample to get total visitors per month
# Write your code here

# 5️⃣ Resample to get average visitors per week
# Write your code here

In [20]:
import pandas as pd

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

data = {
    "VisitDate": [
        "2024-01-01",
        "2024-01-03",
        "2024-01-08",
        "2024-01-15",
        "2024-01-22",
        "2024-02-02",
        "2024-02-10",
        "2024-02-18",
        "2024-03-05",
        "2024-03-12",
        "2024-03-20",
        "2024-03-28"
    ],
    "Visitors": [
        120,
        150,
        180,
        170,
        160,
        200,
        220,
        210,
        250,
        240,
        260,
        270
    ]
}

df = pd.DataFrame(data)

In [21]:
df

     VisitDate  Visitors
0   2024-01-01       120
1   2024-01-03       150
2   2024-01-08       180
3   2024-01-15       170
4   2024-01-22       160
5   2024-02-02       200
6   2024-02-10       220
7   2024-02-18       210
8   2024-03-05       250
9   2024-03-12       240
10  2024-03-20       260
11  2024-03-28       270

In [22]:
df['VisitDate'] = pd.to_datetime(df['VisitDate'])

In [23]:
df

    VisitDate  Visitors
0  2024-01-01       120
1  2024-01-03       150
2  2024-01-08       180
3  2024-01-15       170
4  2024-01-22       160
5  2024-02-02       200
6  2024-02-10       220
7  2024-02-18       210
8  2024-03-05       250
9  2024-03-12       240
10 2024-03-20       260
11 2024-03-28       270

In [24]:
df1 = df.set_index('VisitDate')

In [25]:
df1

            Visitors
VisitDate
2024-01-01       120
2024-01-03       150
2024-01-08       180
2024-01-15       170
2024-01-22       160
2024-02-02       200
2024-02-10       220
2024-02-18       210
2024-03-05       250
2024-03-12       240
2024-03-20       260
2024-03-28       270

In [29]:
df1.resample("M")['Visitors'].sum()

/tmp/ipykernel_902/1957032044.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df1.resample("M")['Visitors'].sum()

VisitDate
2024-01-31     780
2024-02-29     630
2024-03-31    1020
Freq: ME, Name: Visitors, dtype: int64

In [30]:
df1.resample("M")['Visitors'].mean()

/tmp/ipykernel_902/2566580917.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df1.resample("M")['Visitors'].mean()

VisitDate
2024-01-31    156.0
2024-02-29    210.0
2024-03-31    255.0
Freq: ME, Name: Visitors, dtype: float64

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.