# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [117]:

# Dataset 1: Product details


# Dataset 2: More products (same columns as df1 → good for vertical stacking)

# Dataset 3: Additional info (different columns → good for horizontal stacking)

In [118]:
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})

# Dataset 2: More products (same columns as df1 - good for vertical concatenation)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})

# Dataset 3: Additional information (different columns - good for horizontal concatenation)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})

In [119]:
df1

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30

In [120]:
df2

   ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser      8

In [121]:
df3

   Stock  Rating
0    100     4.5
1     60     4.7
2     80     4.8

In [122]:
pd.concat([df1,df2])

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [123]:
pd.concat([df1,df2],ignore_index=True)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [124]:
pd.concat([df1,df3],axis=0)

   ProductID ProductName  Price  Stock  Rating
0      101.0         Pen   10.0    NaN     NaN
1      102.0    Notebook   50.0    NaN     NaN
2      103.0      Marker   30.0    NaN     NaN
0        NaN         NaN    NaN  100.0     4.5
1        NaN         NaN    NaN   60.0     4.7
2        NaN         NaN    NaN   80.0     4.8

In [125]:
pd.concat([df1,df3],axis=1)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

In [126]:
pd.concat([df1,df3],axis=1,ignore_index=False)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [127]:
product = pd.concat([df1,df2],ignore_index=False)

In [128]:
product

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [129]:
sales = pd.DataFrame({
    "ProductID":[101,102,104,106],
    "UnitsSold":[500,200,150,50]
})

In [130]:
pd.merge(product,sales)

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [131]:
pd.merge(product,sales,on='ProductID',how='inner')

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [132]:
pd.merge(product,sales,on='ProductID',how='left')

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      8        NaN

In [133]:
pd.merge(product,sales,on='ProductID',how='right')

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50

In [134]:
pd.merge(product,sales,on='ProductID',how='outer')

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

In [135]:
pd.merge(product,sales,on='ProductID',how='inner')

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [136]:
product

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [137]:
stock

     stocks
101     100
102      60
103      80
104     120
105     150

In [138]:
pdata = product.set_index('ProductID')

In [139]:
pdata

          ProductName  Price
ProductID
101               Pen     10
102          Notebook     50
103            Marker     30
104            Pencil      5
105            Eraser      8

In [140]:
pdata.join(stock)

          ProductName  Price  stocks
ProductID
101               Pen     10     100
102          Notebook     50      60
103            Marker     30      80
104            Pencil      5     120
105            Eraser      8     150

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [141]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

In [142]:
import pandas as pd

# Products DataFrame
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductName": [
        "Pen", "Notebook", "Marker", "Pencil", "Eraser",
        "Scale", "Sharpener", "File", "Glue", "Highlighter"
    ],
    "Category": [
        "Stationery", "Stationery", "Stationery", "Stationery", "Stationery",
        "Stationery", "Stationery", "Office", "Office", "Office"
    ],
    "Price": [10, 50, 30, 5, 8, 20, 15, 60, 25, 40]
})

# Sales DataFrame
sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105, 106, 108, 109, 111],
    "UnitsSold": [120, 80, 95, 150, 70, 40, 65, 30],
    "City": [
        "Ahmedabad", "Surat", "Rajkot", "Vadodara",
        "Ahmedabad", "Surat", "Rajkot", "Mumbai"
    ]
})

# Revenue DataFrame
revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105, 107, 108, 110, 112],
    "Revenue": [1200, 4000, 500, 1200, 900, 2400, 1600, 700],
    "Quarter": [
        "Q1", "Q1", "Q2", "Q2",
        "Q3", "Q3", "Q4", "Q4"
    ]
})

In [143]:
products

   ProductID  ProductName    Category  Price
0        101          Pen  Stationery     10
1        102     Notebook  Stationery     50
2        103       Marker  Stationery     30
3        104       Pencil  Stationery      5
4        105       Eraser  Stationery      8
5        106        Scale  Stationery     20
6        107    Sharpener  Stationery     15
7        108         File      Office     60
8        109         Glue      Office     25
9        110  Highlighter      Office     40

In [144]:
sales

   ProductID  UnitsSold       City
0        101        120  Ahmedabad
1        102         80      Surat
2        103         95     Rajkot
3        105        150   Vadodara
4        106         70  Ahmedabad
5        108         40      Surat
6        109         65     Rajkot
7        111         30     Mumbai

In [145]:
revenue

   ProductID  Revenue Quarter
0        101     1200      Q1
1        102     4000      Q1
2        104      500      Q2
3        105     1200      Q2
4        107      900      Q3
5        108     2400      Q3
6        110     1600      Q4
7        112      700      Q4

In [146]:
pd.concat([products,sales],axis = 1)

   ProductID  ProductName    Category  Price  ProductID  UnitsSold       City
0        101          Pen  Stationery     10      101.0      120.0  Ahmedabad
1        102     Notebook  Stationery     50      102.0       80.0      Surat
2        103       Marker  Stationery     30      103.0       95.0     Rajkot
3        104       Pencil  Stationery      5      105.0      150.0   Vadodara
4        105       Eraser  Stationery      8      106.0       70.0  Ahmedabad
5        106        Scale  Stationery     20      108.0       40.0      Surat
6        107    Sharpener  Stationery     15      109.0       65.0     Rajkot
7        108         File      Office     60      111.0       30.0     Mumbai
8        109         Glue      Office     25        NaN        NaN        NaN
9        110  Highlighter      Office     40        NaN        NaN        NaN

In [147]:
pd.concat([products,sales],axis = 0)

   ProductID  ProductName    Category  Price  UnitsSold       City
0        101          Pen  Stationery   10.0        NaN        NaN
1        102     Notebook  Stationery   50.0        NaN        NaN
2        103       Marker  Stationery   30.0        NaN        NaN
3        104       Pencil  Stationery    5.0        NaN        NaN
4        105       Eraser  Stationery    8.0        NaN        NaN
5        106        Scale  Stationery   20.0        NaN        NaN
6        107    Sharpener  Stationery   15.0        NaN        NaN
7        108         File      Office   60.0        NaN        NaN
8        109         Glue      Office   25.0        NaN        NaN
9        110  Highlighter      Office   40.0        NaN        NaN
0        101          NaN         NaN    NaN      120.0  Ahmedabad
1        102          NaN         NaN    NaN       80.0      Surat
2        103          NaN         NaN    NaN       95.0     Rajkot
3        105          NaN         NaN    NaN      150.0   Vadodara
4        106          NaN         NaN    NaN       70.0  Ahmedabad
5        108          NaN         NaN    NaN       40.0      Surat
6        109          NaN         NaN    NaN       65.0     Rajkot
7        111          NaN         NaN    NaN       30.0     Mumbai

In [148]:
pd.merge(sales,revenue,on='ProductID',how='inner')

   ProductID  UnitsSold       City  Revenue Quarter
0        101        120  Ahmedabad     1200      Q1
1        102         80      Surat     4000      Q1
2        105        150   Vadodara     1200      Q2
3        108         40      Surat     2400      Q3

In [149]:
pd.merge(sales,revenue,on='ProductID',how='left')

   ProductID  UnitsSold       City  Revenue Quarter
0        101        120  Ahmedabad   1200.0      Q1
1        102         80      Surat   4000.0      Q1
2        103         95     Rajkot      NaN     NaN
3        105        150   Vadodara   1200.0      Q2
4        106         70  Ahmedabad      NaN     NaN
5        108         40      Surat   2400.0      Q3
6        109         65     Rajkot      NaN     NaN
7        111         30     Mumbai      NaN     NaN

In [150]:
pd.merge(sales,revenue,on='ProductID',how='right')

   ProductID  UnitsSold       City  Revenue Quarter
0        101      120.0  Ahmedabad     1200      Q1
1        102       80.0      Surat     4000      Q1
2        104        NaN        NaN      500      Q2
3        105      150.0   Vadodara     1200      Q2
4        107        NaN        NaN      900      Q3
5        108       40.0      Surat     2400      Q3
6        110        NaN        NaN     1600      Q4
7        112        NaN        NaN      700      Q4

In [151]:
pd.merge(sales,revenue,on='ProductID',how='outer')

    ProductID  UnitsSold       City  Revenue Quarter
0         101      120.0  Ahmedabad   1200.0      Q1
1         102       80.0      Surat   4000.0      Q1
2         103       95.0     Rajkot      NaN     NaN
3         104        NaN        NaN    500.0      Q2
4         105      150.0   Vadodara   1200.0      Q2
5         106       70.0  Ahmedabad      NaN     NaN
6         107        NaN        NaN    900.0      Q3
7         108       40.0      Surat   2400.0      Q3
8         109       65.0     Rajkot      NaN     NaN
9         110        NaN        NaN   1600.0      Q4
10        111       30.0     Mumbai      NaN     NaN
11        112        NaN        NaN    700.0      Q4

In [157]:
psdata = products.set_index("ProductID")

In [158]:
psdata

           ProductName    Category  Price
ProductID
101                Pen  Stationery     10
102           Notebook  Stationery     50
103             Marker  Stationery     30
104             Pencil  Stationery      5
105             Eraser  Stationery      8
106              Scale  Stationery     20
107          Sharpener  Stationery     15
108               File      Office     60
109               Glue      Office     25
110        Highlighter      Office     40

In [161]:
ssdata = sales.set_index("ProductID")

In [162]:
ssdata

           UnitsSold       City
ProductID
101              120  Ahmedabad
102               80      Surat
103               95     Rajkot
105              150   Vadodara
106               70  Ahmedabad
108               40      Surat
109               65     Rajkot
111               30     Mumbai

In [164]:
join =psdata.join(ssdata,on='ProductID')

In [165]:
join

           ProductName    Category  Price  UnitsSold       City
ProductID
101                Pen  Stationery     10      120.0  Ahmedabad
102           Notebook  Stationery     50       80.0      Surat
103             Marker  Stationery     30       95.0     Rajkot
104             Pencil  Stationery      5        NaN        NaN
105             Eraser  Stationery      8      150.0   Vadodara
106              Scale  Stationery     20       70.0  Ahmedabad
107          Sharpener  Stationery     15        NaN        NaN
108               File      Office     60       40.0      Surat
109               Glue      Office     25       65.0     Rajkot
110        Highlighter      Office     40        NaN        NaN

In [166]:
join.isna()

           ProductName  Category  Price  UnitsSold   City
ProductID
101              False     False  False      False  False
102              False     False  False      False  False
103              False     False  False      False  False
104              False     False  False       True   True
105              False     False  False      False  False
106              False     False  False      False  False
107              False     False  False       True   True
108              False     False  False      False  False
109              False     False  False      False  False
110              False     False  False       True   True

In [167]:
join.isna().sum()

ProductName    0
Category       0
Price          0
UnitsSold      3
City           3
dtype: int64

In [168]:
join.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 101 to 110
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductName  10 non-null     object
 1   Category     10 non-null     object
 2   Price        10 non-null     int64
 3   UnitsSold    7 non-null      float64
 4   City         7 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 480.0+ bytes

In [169]:
join.describe()

           Price   UnitsSold
count  10.000000    7.000000
mean   26.300000   88.571429
std    18.625252   36.823259
min     5.000000   40.000000
25%    11.250000   67.500000
50%    22.500000   80.000000
75%    37.500000  107.500000
max    60.000000  150.000000

In [171]:
join[join.isna().any(axis=1)]

           ProductName    Category  Price  UnitsSold City
ProductID
104             Pencil  Stationery      5        NaN  NaN
107          Sharpener  Stationery     15        NaN  NaN
110        Highlighter      Office     40        NaN  NaN

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.