# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [5]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)

In [6]:
df

      Name  Math  Science
0    Alice    88       90
1      Bob    75       80
2  Charlie    92       78
3    David    60       70
4     Emma    85       95

In [14]:
df['total Marks'] = df[['Math','Science']].apply(lambda row : row.sum(),axis = 1)

In [15]:
df

      Name  Math  Science  total Marks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [16]:
col_mean = df[['Math','Science']].apply(lambda col : col.mean())

In [17]:
col_mean

Math       80.0
Science    82.6
dtype: float64

In [19]:
def grade(s):
  if s>=90:
    return "A"
  elif s>=75:
    return "B"
  if s>=60:
    return "C"
  if s>=55:
    return "D"
  else:
    return "FAIL"

In [20]:
df['MathGrade'] = df['Math'].apply(grade)

In [21]:
df['ScienceGrade'] = df['Science'].apply(grade)

In [22]:
df

      Name  Math  Science  total Marks MathGrade ScienceGrade
0    Alice    88       90          178         B            A
1      Bob    75       80          155         B            B
2  Charlie    92       78          170         A            B
3    David    60       70          130         C            C
4     Emma    85       95          180         B            A

In [23]:
df['Name'] = df['Name'].map(str.lower)

In [24]:
df

      Name  Math  Science  total Marks MathGrade ScienceGrade
0    alice    88       90          178         B            A
1      bob    75       80          155         B            B
2  charlie    92       78          170         A            B
3    david    60       70          130         C            C
4     emma    85       95          180         B            A

In [25]:
df['bonus marks'] = df['total Marks'].map(lambda x : x+10)

In [26]:
df

      Name  Math  Science  total Marks MathGrade ScienceGrade  bonus marks
0    alice    88       90          178         B            A          188
1      bob    75       80          155         B            B          165
2  charlie    92       78          170         A            B          180
3    david    60       70          130         C            C          140
4     emma    85       95          180         B            A          190