# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [13]:
import pandas as pd

data = {
    "Product": ["Pen", "Notebook", "Pencil", "Marker", "Eraser", "Sharpener"],
    "Price": [10, 50, 5, 30, 8, 12],
    "Stock": [100, 60, 200, 80, 150, 120],
    "Rating": [4.5, 4.7, 4.2, 4.8, 4.3, 4.4]
}

df = pd.DataFrame(data)

In [14]:
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [15]:
df.sort_values(by = "Price")

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [16]:
df.sort_values(by = "Price",ascending=False)

     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [17]:
df.sort_values(by = ['Price','Stock'],ascending=[True,False])

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [18]:
df.mean(numeric_only=True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [19]:
df.median(numeric_only=True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [20]:
df.mode()

     Product  Price  Stock  Rating
0     Eraser      5     60     4.2
1     Marker      8     80     4.3
2   Notebook     10    100     4.4
3        Pen     12    120     4.5
4     Pencil     30    150     4.7
5  Sharpener     50    200     4.8

In [23]:
df.std(numeric_only=True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [22]:
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [24]:
df['Product'].value_counts()

Product
Pen          1
Notebook     1
Pencil       1
Marker       1
Eraser       1
Sharpener    1
Name: count, dtype: int64

In [25]:
df['Rating'].value_counts()

Rating
4.5    1
4.7    1
4.2    1
4.8    1
4.3    1
4.4    1
Name: count, dtype: int64

In [26]:
df['Stock'].value_counts(normalize=True)

Stock
100    0.166667
60     0.166667
200    0.166667
80     0.166667
150    0.166667
120    0.166667
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [27]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [28]:
df.cov(numeric_only=True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [30]:
df['Price'].corr(df['Rating'])

np.float64(0.8204016469535791)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [21]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

# 2. Sort the data by Score (descending)
# Write your code here

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

# 4. Use value_counts on Name or any categorical column
# Write your code here

# 5. Compute corr() and cov() for all numeric columns
# Write your code here

In [33]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95],
    "Height": [160, 175, 168, 180, 158]
}

df = pd.DataFrame(data)

In [34]:
df

      Name  Age  Score  Height
0    Alice   25     88     160
1      Bob   30     92     175
2  Charlie   35     79     168
3    David   40     85     180
4     Emma   22     95     158

In [35]:
df.sort_values(by='Score',ascending=False)

      Name  Age  Score  Height
4     Emma   22     95     158
1      Bob   30     92     175
0    Alice   25     88     160
3    David   40     85     180
2  Charlie   35     79     168

In [36]:
df.mean(numeric_only=True)

Age        30.4
Score      87.8
Height    168.2
dtype: float64

In [37]:
df.median(numeric_only=True)

Age        30.0
Score      88.0
Height    168.0
dtype: float64

In [38]:
df.mode()

      Name  Age  Score  Height
0    Alice   22     79     158
1      Bob   25     85     160
2  Charlie   30     88     168
3    David   35     92     175
4     Emma   40     95     180

In [39]:
df.std(numeric_only=True)

Age       7.300685
Score     6.220932
Height    9.444575
dtype: float64

In [40]:
df.value_counts('Name')

Name
Alice      1
Bob        1
Charlie    1
David      1
Emma       1
Name: count, dtype: int64

In [41]:
df.corr(numeric_only=True)

             Age     Score    Height
Age     1.000000 -0.718893  0.868722
Score  -0.718893  1.000000 -0.331041
Height  0.868722 -0.331041  1.000000

In [42]:
df.cov(numeric_only=True)

          Age  Score  Height
Age     53.30 -32.65   59.90
Score  -32.65  38.70  -19.45
Height  59.90 -19.45   89.20

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.