# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
import numpy as np

a = {
    "Name": ['Alice','Bob','Charli','David','Emma'],
    "Age":[29,30,35,40,22],
    "Score":[88,92,79,85,95]
}

b = pd.DataFrame(a)
b

     Name  Age  Score
0   Alice   29     88
1     Bob   30     92
2  Charli   35     79
3   David   40     85
4    Emma   22     95

In [ ]:
b['Age'] > 30

0    False
1    False
2     True
3     True
4    False
Name: Age, dtype: bool

In [ ]:
b[b['Age']>30]

     Name  Age  Score
2  Charli   35     79
3   David   40     85

In [ ]:
b[(b['Age']>25) & (b['Score'] > 85)]

    Name  Age  Score
0  Alice   29     88
1    Bob   30     92

In [ ]:
b[(b['Age']<25) | (b['Score'] > 90)]

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

In [ ]:
b[~ (b['Score']>85)]

     Name  Age  Score
2  Charli   35     79
3   David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
b[(b['Age']>25) & (b['Score'] > 85)]

    Name  Age  Score
0  Alice   29     88
1    Bob   30     92

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
b

     Name  Age  Score
0   Alice   29     88
1     Bob   30     92
2  Charli   35     79
3   David   40     85
4    Emma   22     95

In [ ]:
b.query("Age > 25")

     Name  Age  Score
0   Alice   29     88
1     Bob   30     92
2  Charli   35     79
3   David   40     85

In [ ]:
b.query("Age > 25 and Score >90")

  Name  Age  Score
1  Bob   30     92

In [ ]:
hold = 90
b.query("Score > @hold")

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
b

     Name  Age  Score
0   Alice   29     88
1     Bob   30     92
2  Charli   35     79
3   David   40     85
4    Emma   22     95

In [ ]:
b['Name'].str.lower()

0     alice
1       bob
2    charli
3     david
4      emma
Name: Name, dtype: object

In [ ]:
b[b['Name'].str.contains("a",case=False)]

     Name  Age  Score
0   Alice   29     88
2  Charli   35     79
3   David   40     85
4    Emma   22     95

In [ ]:
b['Name'].str.lower()

0     alice
1       bob
2    charli
3     david
4      emma
Name: Name, dtype: object

In [ ]:
b['Name'].str.startswith("D")

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [ ]:
b['Name'].str.endswith("a")

0    False
1    False
2    False
3    False
4     True
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 22, 28, 24],
    "City": ["New York", "London", "Paris", "Tokyo", "Sydney"],
    "Score": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)

In [ ]:
df

      Name  Age      City  Score
0    Alice   25  New York     85
1      Bob   30    London     90
2  Charlie   22     Paris     78
3    David   28     Tokyo     88
4     Emma   24    Sydney     92

In [ ]:
df[df['Age']>25]

    Name  Age    City  Score
1    Bob   30  London     90
3  David   28   Tokyo     88

In [ ]:
df[(df['City']=="London") |(df['City']=="Tokyo")]

    Name  Age    City  Score
1    Bob   30  London     90
3  David   28   Tokyo     88

In [ ]:
df.query("Score>=85 and Age <35")

    Name  Age      City  Score
0  Alice   25  New York     85
1    Bob   30    London     90
3  David   28     Tokyo     88
4   Emma   24    Sydney     92

In [ ]:
df['City'].str.lower()

0    new york
1      london
2       paris
3       tokyo
4      sydney
Name: City, dtype: object

In [ ]:
df['City'].replace("Paris","New Delhi")

0     New York
1       London
2    New Delhi
3        Tokyo
4       Sydney
Name: City, dtype: object

In [ ]:
df

      Name  Age      City  Score
0    Alice   25  New York     85
1      Bob   30    London     90
2  Charlie   22     Paris     78
3    David   28     Tokyo     88
4     Emma   24    Sydney     92

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.